export const FETCH_ITEMS = "FETCH_ITEMS";
export const FETCH_ITEMS_REQUEST = "FETCH_ITEMS_REQUEST";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAILURE = "FETCH_ITEMS_FAILURE";
export const INCREMENT_PAGE_NO = "INCREMENT_PAGE_NO";
export const DECREMENT_PAGE_NO = "DECREMENT_PAGE_NO";
